# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_gui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1319, 829)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_1 = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_1.sizePolicy().hasHeightForWidth())
        self.frame_1.setSizePolicy(sizePolicy)
        self.frame_1.setMinimumSize(QtCore.QSize(450, 480))
        self.frame_1.setMaximumSize(QtCore.QSize(450, 1000))
        self.frame_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_1.setObjectName("frame_1")
        self.label_messages = QtWidgets.QLabel(self.frame_1)
        self.label_messages.setGeometry(QtCore.QRect(10, 580, 431, 141))
        self.label_messages.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_messages.setText("")
        self.label_messages.setWordWrap(True)
        self.label_messages.setObjectName("label_messages")
        self.label_10 = QtWidgets.QLabel(self.frame_1)
        self.label_10.setGeometry(QtCore.QRect(10, 560, 81, 16))
        self.label_10.setObjectName("label_10")
        self.label_acquisition_progress = QtWidgets.QLabel(self.frame_1)
        self.label_acquisition_progress.setGeometry(QtCore.QRect(280, 110, 101, 16))
        self.label_acquisition_progress.setText("")
        self.label_acquisition_progress.setObjectName("label_acquisition_progress")
        self.tabWidget = QtWidgets.QTabWidget(self.frame_1)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QtCore.QRect(20, 10, 440, 551))
        self.tabWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget.setObjectName("tabWidget")
        self.SEM = QtWidgets.QWidget()
        self.SEM.setObjectName("SEM")
        self.label_3 = QtWidgets.QLabel(self.SEM)
        self.label_3.setGeometry(QtCore.QRect(10, 60, 161, 20))
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(self.SEM)
        self.label_2.setGeometry(QtCore.QRect(20, 160, 91, 16))
        self.label_2.setObjectName("label_2")
        self.spinBox_horizontal_field_width = QtWidgets.QDoubleSpinBox(self.SEM)
        self.spinBox_horizontal_field_width.setGeometry(QtCore.QRect(10, 80, 81, 22))
        self.spinBox_horizontal_field_width.setMaximum(10000000.0)
        self.spinBox_horizontal_field_width.setProperty("value", 100.0)
        self.spinBox_horizontal_field_width.setObjectName("spinBox_horizontal_field_width")
        self.spinBox_dwell_time = QtWidgets.QDoubleSpinBox(self.SEM)
        self.spinBox_dwell_time.setGeometry(QtCore.QRect(110, 160, 81, 22))
        self.spinBox_dwell_time.setMaximum(10000000.0)
        self.spinBox_dwell_time.setProperty("value", 0.1)
        self.spinBox_dwell_time.setObjectName("spinBox_dwell_time")
        self.pushButton_select_directory = QtWidgets.QPushButton(self.SEM)
        self.pushButton_select_directory.setGeometry(QtCore.QRect(290, 30, 121, 28))
        self.pushButton_select_directory.setObjectName("pushButton_select_directory")
        self.comboBox_resolution = QtWidgets.QComboBox(self.SEM)
        self.comboBox_resolution.setGeometry(QtCore.QRect(10, 30, 91, 22))
        self.comboBox_resolution.setObjectName("comboBox_resolution")
        self.comboBox_resolution.addItem("")
        self.comboBox_resolution.addItem("")
        self.comboBox_resolution.addItem("")
        self.comboBox_resolution.addItem("")
        self.comboBox_resolution.addItem("")
        self.comboBox_resolution.addItem("")
        self.comboBox_resolution.addItem("")
        self.comboBox_resolution.addItem("")
        self.label_28 = QtWidgets.QLabel(self.SEM)
        self.label_28.setGeometry(QtCore.QRect(10, 10, 101, 16))
        self.label_28.setObjectName("label_28")
        self.checkBox_autocontrast = QtWidgets.QCheckBox(self.SEM)
        self.checkBox_autocontrast.setEnabled(True)
        self.checkBox_autocontrast.setGeometry(QtCore.QRect(300, 80, 111, 20))
        self.checkBox_autocontrast.setChecked(False)
        self.checkBox_autocontrast.setObjectName("checkBox_autocontrast")
        self.checkBox_drift_correction = QtWidgets.QCheckBox(self.SEM)
        self.checkBox_drift_correction.setGeometry(QtCore.QRect(240, 270, 111, 20))
        self.checkBox_drift_correction.setChecked(True)
        self.checkBox_drift_correction.setObjectName("checkBox_drift_correction")
        self.comboBox_beam_type = QtWidgets.QComboBox(self.SEM)
        self.comboBox_beam_type.setGeometry(QtCore.QRect(180, 30, 81, 22))
        self.comboBox_beam_type.setObjectName("comboBox_beam_type")
        self.comboBox_beam_type.addItem("")
        self.comboBox_beam_type.addItem("")
        self.label_4 = QtWidgets.QLabel(self.SEM)
        self.label_4.setGeometry(QtCore.QRect(180, 10, 41, 16))
        self.label_4.setObjectName("label_4")
        self.comboBox_quadrant = QtWidgets.QComboBox(self.SEM)
        self.comboBox_quadrant.setGeometry(QtCore.QRect(180, 80, 73, 22))
        self.comboBox_quadrant.setObjectName("comboBox_quadrant")
        self.comboBox_quadrant.addItem("")
        self.comboBox_quadrant.addItem("")
        self.comboBox_quadrant.addItem("")
        self.comboBox_quadrant.addItem("")
        self.label_8 = QtWidgets.QLabel(self.SEM)
        self.label_8.setGeometry(QtCore.QRect(180, 60, 61, 16))
        self.label_8.setObjectName("label_8")
        self.doubleSpinBox_hfw_01 = QtWidgets.QDoubleSpinBox(self.SEM)
        self.doubleSpinBox_hfw_01.setGeometry(QtCore.QRect(110, 220, 81, 22))
        self.doubleSpinBox_hfw_01.setDecimals(5)
        self.doubleSpinBox_hfw_01.setMaximum(1000000.0)
        self.doubleSpinBox_hfw_01.setProperty("value", 0.4144)
        self.doubleSpinBox_hfw_01.setObjectName("doubleSpinBox_hfw_01")
        self.label_5 = QtWidgets.QLabel(self.SEM)
        self.label_5.setGeometry(QtCore.QRect(110, 200, 151, 16))
        self.label_5.setObjectName("label_5")
        self.doubleSpinBox_hfw_02 = QtWidgets.QDoubleSpinBox(self.SEM)
        self.doubleSpinBox_hfw_02.setGeometry(QtCore.QRect(110, 240, 81, 22))
        self.doubleSpinBox_hfw_02.setDecimals(5)
        self.doubleSpinBox_hfw_02.setMaximum(1000000.0)
        self.doubleSpinBox_hfw_02.setProperty("value", 0.518)
        self.doubleSpinBox_hfw_02.setObjectName("doubleSpinBox_hfw_02")
        self.doubleSpinBox_hfw_03 = QtWidgets.QDoubleSpinBox(self.SEM)
        self.doubleSpinBox_hfw_03.setGeometry(QtCore.QRect(110, 260, 81, 22))
        self.doubleSpinBox_hfw_03.setDecimals(5)
        self.doubleSpinBox_hfw_03.setMaximum(1000000.0)
        self.doubleSpinBox_hfw_03.setProperty("value", 0.8288)
        self.doubleSpinBox_hfw_03.setObjectName("doubleSpinBox_hfw_03")
        self.doubleSpinBox_hfw_04 = QtWidgets.QDoubleSpinBox(self.SEM)
        self.doubleSpinBox_hfw_04.setGeometry(QtCore.QRect(110, 280, 81, 22))
        self.doubleSpinBox_hfw_04.setDecimals(5)
        self.doubleSpinBox_hfw_04.setMaximum(1000000.0)
        self.doubleSpinBox_hfw_04.setProperty("value", 1.6576)
        self.doubleSpinBox_hfw_04.setObjectName("doubleSpinBox_hfw_04")
        self.doubleSpinBox_hfw_05 = QtWidgets.QDoubleSpinBox(self.SEM)
        self.doubleSpinBox_hfw_05.setGeometry(QtCore.QRect(110, 300, 81, 22))
        self.doubleSpinBox_hfw_05.setDecimals(5)
        self.doubleSpinBox_hfw_05.setMaximum(1000000.0)
        self.doubleSpinBox_hfw_05.setProperty("value", 4.144)
        self.doubleSpinBox_hfw_05.setObjectName("doubleSpinBox_hfw_05")
        self.doubleSpinBox_hfw_06 = QtWidgets.QDoubleSpinBox(self.SEM)
        self.doubleSpinBox_hfw_06.setGeometry(QtCore.QRect(110, 320, 81, 22))
        self.doubleSpinBox_hfw_06.setDecimals(5)
        self.doubleSpinBox_hfw_06.setMaximum(1000000.0)
        self.doubleSpinBox_hfw_06.setProperty("value", 8.288)
        self.doubleSpinBox_hfw_06.setObjectName("doubleSpinBox_hfw_06")
        self.doubleSpinBox_hfw_07 = QtWidgets.QDoubleSpinBox(self.SEM)
        self.doubleSpinBox_hfw_07.setGeometry(QtCore.QRect(110, 340, 81, 22))
        self.doubleSpinBox_hfw_07.setDecimals(5)
        self.doubleSpinBox_hfw_07.setMaximum(1000000.0)
        self.doubleSpinBox_hfw_07.setProperty("value", 20.72)
        self.doubleSpinBox_hfw_07.setObjectName("doubleSpinBox_hfw_07")
        self.doubleSpinBox_hfw_08 = QtWidgets.QDoubleSpinBox(self.SEM)
        self.doubleSpinBox_hfw_08.setGeometry(QtCore.QRect(110, 360, 81, 22))
        self.doubleSpinBox_hfw_08.setDecimals(5)
        self.doubleSpinBox_hfw_08.setMaximum(1000000.0)
        self.doubleSpinBox_hfw_08.setProperty("value", 41.44)
        self.doubleSpinBox_hfw_08.setObjectName("doubleSpinBox_hfw_08")
        self.doubleSpinBox_hfw_09 = QtWidgets.QDoubleSpinBox(self.SEM)
        self.doubleSpinBox_hfw_09.setGeometry(QtCore.QRect(110, 380, 81, 22))
        self.doubleSpinBox_hfw_09.setDecimals(5)
        self.doubleSpinBox_hfw_09.setMaximum(1000000.0)
        self.doubleSpinBox_hfw_09.setProperty("value", 82.88)
        self.doubleSpinBox_hfw_09.setObjectName("doubleSpinBox_hfw_09")
        self.doubleSpinBox_hfw_10 = QtWidgets.QDoubleSpinBox(self.SEM)
        self.doubleSpinBox_hfw_10.setGeometry(QtCore.QRect(110, 400, 81, 22))
        self.doubleSpinBox_hfw_10.setDecimals(5)
        self.doubleSpinBox_hfw_10.setMaximum(1000000.0)
        self.doubleSpinBox_hfw_10.setProperty("value", 165.76)
        self.doubleSpinBox_hfw_10.setObjectName("doubleSpinBox_hfw_10")
        self.doubleSpinBox_hfw_11 = QtWidgets.QDoubleSpinBox(self.SEM)
        self.doubleSpinBox_hfw_11.setGeometry(QtCore.QRect(110, 420, 81, 22))
        self.doubleSpinBox_hfw_11.setDecimals(5)
        self.doubleSpinBox_hfw_11.setMaximum(1000000.0)
        self.doubleSpinBox_hfw_11.setProperty("value", 414.4)
        self.doubleSpinBox_hfw_11.setObjectName("doubleSpinBox_hfw_11")
        self.doubleSpinBox_hfw_12 = QtWidgets.QDoubleSpinBox(self.SEM)
        self.doubleSpinBox_hfw_12.setGeometry(QtCore.QRect(110, 440, 81, 22))
        self.doubleSpinBox_hfw_12.setDecimals(5)
        self.doubleSpinBox_hfw_12.setMaximum(1000000.0)
        self.doubleSpinBox_hfw_12.setProperty("value", 828.8)
        self.doubleSpinBox_hfw_12.setObjectName("doubleSpinBox_hfw_12")
        self.checkBox_hfw_01 = QtWidgets.QCheckBox(self.SEM)
        self.checkBox_hfw_01.setGeometry(QtCore.QRect(90, 220, 21, 20))
        self.checkBox_hfw_01.setText("")
        self.checkBox_hfw_01.setChecked(True)
        self.checkBox_hfw_01.setObjectName("checkBox_hfw_01")
        self.checkBox_hfw_02 = QtWidgets.QCheckBox(self.SEM)
        self.checkBox_hfw_02.setGeometry(QtCore.QRect(90, 240, 21, 20))
        self.checkBox_hfw_02.setText("")
        self.checkBox_hfw_02.setChecked(True)
        self.checkBox_hfw_02.setObjectName("checkBox_hfw_02")
        self.checkBox_hfw_03 = QtWidgets.QCheckBox(self.SEM)
        self.checkBox_hfw_03.setGeometry(QtCore.QRect(90, 260, 21, 20))
        self.checkBox_hfw_03.setText("")
        self.checkBox_hfw_03.setChecked(True)
        self.checkBox_hfw_03.setObjectName("checkBox_hfw_03")
        self.checkBox_hfw_04 = QtWidgets.QCheckBox(self.SEM)
        self.checkBox_hfw_04.setGeometry(QtCore.QRect(90, 280, 21, 20))
        self.checkBox_hfw_04.setText("")
        self.checkBox_hfw_04.setChecked(True)
        self.checkBox_hfw_04.setObjectName("checkBox_hfw_04")
        self.checkBox_hfw_05 = QtWidgets.QCheckBox(self.SEM)
        self.checkBox_hfw_05.setGeometry(QtCore.QRect(90, 300, 21, 20))
        self.checkBox_hfw_05.setText("")
        self.checkBox_hfw_05.setChecked(True)
        self.checkBox_hfw_05.setObjectName("checkBox_hfw_05")
        self.checkBox_hfw_06 = QtWidgets.QCheckBox(self.SEM)
        self.checkBox_hfw_06.setGeometry(QtCore.QRect(90, 320, 21, 20))
        self.checkBox_hfw_06.setText("")
        self.checkBox_hfw_06.setChecked(True)
        self.checkBox_hfw_06.setObjectName("checkBox_hfw_06")
        self.checkBox_hfw_07 = QtWidgets.QCheckBox(self.SEM)
        self.checkBox_hfw_07.setGeometry(QtCore.QRect(90, 340, 21, 20))
        self.checkBox_hfw_07.setText("")
        self.checkBox_hfw_07.setChecked(True)
        self.checkBox_hfw_07.setObjectName("checkBox_hfw_07")
        self.checkBox_hfw_08 = QtWidgets.QCheckBox(self.SEM)
        self.checkBox_hfw_08.setGeometry(QtCore.QRect(90, 360, 21, 20))
        self.checkBox_hfw_08.setText("")
        self.checkBox_hfw_08.setChecked(True)
        self.checkBox_hfw_08.setObjectName("checkBox_hfw_08")
        self.checkBox_hfw_09 = QtWidgets.QCheckBox(self.SEM)
        self.checkBox_hfw_09.setGeometry(QtCore.QRect(90, 380, 21, 20))
        self.checkBox_hfw_09.setText("")
        self.checkBox_hfw_09.setChecked(False)
        self.checkBox_hfw_09.setObjectName("checkBox_hfw_09")
        self.checkBox_hfw_10 = QtWidgets.QCheckBox(self.SEM)
        self.checkBox_hfw_10.setGeometry(QtCore.QRect(90, 400, 21, 20))
        self.checkBox_hfw_10.setText("")
        self.checkBox_hfw_10.setChecked(False)
        self.checkBox_hfw_10.setObjectName("checkBox_hfw_10")
        self.checkBox_hfw_11 = QtWidgets.QCheckBox(self.SEM)
        self.checkBox_hfw_11.setGeometry(QtCore.QRect(90, 420, 21, 20))
        self.checkBox_hfw_11.setText("")
        self.checkBox_hfw_11.setChecked(False)
        self.checkBox_hfw_11.setObjectName("checkBox_hfw_11")
        self.checkBox_hfw_12 = QtWidgets.QCheckBox(self.SEM)
        self.checkBox_hfw_12.setGeometry(QtCore.QRect(90, 440, 21, 20))
        self.checkBox_hfw_12.setText("")
        self.checkBox_hfw_12.setChecked(False)
        self.checkBox_hfw_12.setObjectName("checkBox_hfw_12")
        self.pushButton_abort_stack_collection = QtWidgets.QPushButton(self.SEM)
        self.pushButton_abort_stack_collection.setGeometry(QtCore.QRect(260, 460, 121, 28))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.NoAntialias)
        self.pushButton_abort_stack_collection.setFont(font)
        self.pushButton_abort_stack_collection.setObjectName("pushButton_abort_stack_collection")
        self.pushButton_collect_stack = QtWidgets.QPushButton(self.SEM)
        self.pushButton_collect_stack.setGeometry(QtCore.QRect(230, 360, 171, 91))
        self.pushButton_collect_stack.setObjectName("pushButton_collect_stack")
        self.label_6 = QtWidgets.QLabel(self.SEM)
        self.label_6.setGeometry(QtCore.QRect(220, 260, 91, 16))
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.plainTextEdit_sample_name = QtWidgets.QPlainTextEdit(self.SEM)
        self.plainTextEdit_sample_name.setGeometry(QtCore.QRect(200, 160, 211, 31))
        self.plainTextEdit_sample_name.setObjectName("plainTextEdit_sample_name")
        self.label_12 = QtWidgets.QLabel(self.SEM)
        self.label_12.setGeometry(QtCore.QRect(240, 300, 111, 16))
        self.label_12.setObjectName("label_12")
        self.spinBox_frame_integration = QtWidgets.QSpinBox(self.SEM)
        self.spinBox_frame_integration.setGeometry(QtCore.QRect(240, 320, 91, 22))
        self.spinBox_frame_integration.setMaximum(1000000)
        self.spinBox_frame_integration.setProperty("value", 1)
        self.spinBox_frame_integration.setObjectName("spinBox_frame_integration")
        self.label_13 = QtWidgets.QLabel(self.SEM)
        self.label_13.setGeometry(QtCore.QRect(10, 200, 91, 16))
        self.label_13.setObjectName("label_13")
        self.label_hfw_01 = QtWidgets.QLabel(self.SEM)
        self.label_hfw_01.setGeometry(QtCore.QRect(50, 220, 21, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.label_hfw_01.setFont(font)
        self.label_hfw_01.setObjectName("label_hfw_01")
        self.label_hfw_02 = QtWidgets.QLabel(self.SEM)
        self.label_hfw_02.setGeometry(QtCore.QRect(50, 240, 31, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.label_hfw_02.setFont(font)
        self.label_hfw_02.setObjectName("label_hfw_02")
        self.label_hfw_03 = QtWidgets.QLabel(self.SEM)
        self.label_hfw_03.setGeometry(QtCore.QRect(50, 260, 31, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.label_hfw_03.setFont(font)
        self.label_hfw_03.setObjectName("label_hfw_03")
        self.label_hfw_04 = QtWidgets.QLabel(self.SEM)
        self.label_hfw_04.setGeometry(QtCore.QRect(50, 280, 31, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.label_hfw_04.setFont(font)
        self.label_hfw_04.setObjectName("label_hfw_04")
        self.label_hfw_05 = QtWidgets.QLabel(self.SEM)
        self.label_hfw_05.setGeometry(QtCore.QRect(50, 300, 31, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.label_hfw_05.setFont(font)
        self.label_hfw_05.setObjectName("label_hfw_05")
        self.label_hfw_06 = QtWidgets.QLabel(self.SEM)
        self.label_hfw_06.setGeometry(QtCore.QRect(50, 320, 21, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.label_hfw_06.setFont(font)
        self.label_hfw_06.setObjectName("label_hfw_06")
        self.label_hfw_07 = QtWidgets.QLabel(self.SEM)
        self.label_hfw_07.setGeometry(QtCore.QRect(50, 340, 21, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.label_hfw_07.setFont(font)
        self.label_hfw_07.setObjectName("label_hfw_07")
        self.label_hfw_08 = QtWidgets.QLabel(self.SEM)
        self.label_hfw_08.setGeometry(QtCore.QRect(50, 360, 21, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.label_hfw_08.setFont(font)
        self.label_hfw_08.setObjectName("label_hfw_08")
        self.label_hfw_09 = QtWidgets.QLabel(self.SEM)
        self.label_hfw_09.setGeometry(QtCore.QRect(50, 380, 21, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.label_hfw_09.setFont(font)
        self.label_hfw_09.setObjectName("label_hfw_09")
        self.label_hfw_10 = QtWidgets.QLabel(self.SEM)
        self.label_hfw_10.setGeometry(QtCore.QRect(50, 400, 31, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.label_hfw_10.setFont(font)
        self.label_hfw_10.setObjectName("label_hfw_10")
        self.label_hfw_11 = QtWidgets.QLabel(self.SEM)
        self.label_hfw_11.setGeometry(QtCore.QRect(50, 420, 21, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.label_hfw_11.setFont(font)
        self.label_hfw_11.setObjectName("label_hfw_11")
        self.label_hfw_12 = QtWidgets.QLabel(self.SEM)
        self.label_hfw_12.setGeometry(QtCore.QRect(50, 440, 21, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.label_hfw_12.setFont(font)
        self.label_hfw_12.setObjectName("label_hfw_12")
        self.checkBox_q1 = QtWidgets.QCheckBox(self.SEM)
        self.checkBox_q1.setGeometry(QtCore.QRect(240, 230, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_q1.setFont(font)
        self.checkBox_q1.setChecked(True)
        self.checkBox_q1.setObjectName("checkBox_q1")
        self.checkBox_q2 = QtWidgets.QCheckBox(self.SEM)
        self.checkBox_q2.setGeometry(QtCore.QRect(310, 230, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_q2.setFont(font)
        self.checkBox_q2.setChecked(False)
        self.checkBox_q2.setObjectName("checkBox_q2")
        self.tabWidget.addTab(self.SEM, "")
        self.Settings = QtWidgets.QWidget()
        self.Settings.setObjectName("Settings")
        self.spinBox_magnification = QtWidgets.QSpinBox(self.Settings)
        self.spinBox_magnification.setGeometry(QtCore.QRect(110, 80, 80, 22))
        self.spinBox_magnification.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.spinBox_magnification.setMinimum(0)
        self.spinBox_magnification.setMaximum(1000000)
        self.spinBox_magnification.setObjectName("spinBox_magnification")
        self.label_16 = QtWidgets.QLabel(self.Settings)
        self.label_16.setGeometry(QtCore.QRect(10, 80, 81, 16))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.Settings)
        self.label_17.setGeometry(QtCore.QRect(10, 110, 101, 21))
        self.label_17.setObjectName("label_17")
        self.doubleSpinBox_high_voltage = QtWidgets.QDoubleSpinBox(self.Settings)
        self.doubleSpinBox_high_voltage.setGeometry(QtCore.QRect(110, 110, 80, 22))
        self.doubleSpinBox_high_voltage.setMaximum(30.0)
        self.doubleSpinBox_high_voltage.setObjectName("doubleSpinBox_high_voltage")
        self.doubleSpinBox_working_distance = QtWidgets.QDoubleSpinBox(self.Settings)
        self.doubleSpinBox_working_distance.setGeometry(QtCore.QRect(110, 170, 80, 22))
        self.doubleSpinBox_working_distance.setObjectName("doubleSpinBox_working_distance")
        self.label_18 = QtWidgets.QLabel(self.Settings)
        self.label_18.setGeometry(QtCore.QRect(10, 170, 101, 16))
        self.label_18.setObjectName("label_18")
        self.doubleSpinBox_brightness = QtWidgets.QDoubleSpinBox(self.Settings)
        self.doubleSpinBox_brightness.setGeometry(QtCore.QRect(110, 200, 80, 22))
        self.doubleSpinBox_brightness.setMaximum(100.0)
        self.doubleSpinBox_brightness.setObjectName("doubleSpinBox_brightness")
        self.label_19 = QtWidgets.QLabel(self.Settings)
        self.label_19.setGeometry(QtCore.QRect(10, 200, 101, 21))
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.Settings)
        self.label_20.setGeometry(QtCore.QRect(10, 230, 101, 16))
        self.label_20.setObjectName("label_20")
        self.doubleSpinBox_contrast = QtWidgets.QDoubleSpinBox(self.Settings)
        self.doubleSpinBox_contrast.setGeometry(QtCore.QRect(110, 230, 80, 22))
        self.doubleSpinBox_contrast.setMaximum(100.0)
        self.doubleSpinBox_contrast.setObjectName("doubleSpinBox_contrast")
        self.label_21 = QtWidgets.QLabel(self.Settings)
        self.label_21.setGeometry(QtCore.QRect(10, 140, 101, 16))
        self.label_21.setObjectName("label_21")
        self.doubleSpinBox_beam_current = QtWidgets.QDoubleSpinBox(self.Settings)
        self.doubleSpinBox_beam_current.setGeometry(QtCore.QRect(110, 140, 80, 22))
        self.doubleSpinBox_beam_current.setObjectName("doubleSpinBox_beam_current")
        self.pushButton_update_SEM_state = QtWidgets.QPushButton(self.Settings)
        self.pushButton_update_SEM_state.setGeometry(QtCore.QRect(10, 260, 181, 31))
        self.pushButton_update_SEM_state.setObjectName("pushButton_update_SEM_state")
        self.label_32 = QtWidgets.QLabel(self.Settings)
        self.label_32.setGeometry(QtCore.QRect(290, 20, 51, 16))
        self.label_32.setObjectName("label_32")
        self.spinBox_average = QtWidgets.QSpinBox(self.Settings)
        self.spinBox_average.setGeometry(QtCore.QRect(340, 18, 71, 22))
        self.spinBox_average.setMinimum(1)
        self.spinBox_average.setMaximum(8000)
        self.spinBox_average.setObjectName("spinBox_average")
        self.label_29 = QtWidgets.QLabel(self.Settings)
        self.label_29.setGeometry(QtCore.QRect(10, 20, 51, 16))
        self.label_29.setObjectName("label_29")
        self.comboBox_bit_depth = QtWidgets.QComboBox(self.Settings)
        self.comboBox_bit_depth.setGeometry(QtCore.QRect(70, 17, 61, 22))
        self.comboBox_bit_depth.setObjectName("comboBox_bit_depth")
        self.comboBox_bit_depth.addItem("")
        self.comboBox_bit_depth.addItem("")
        self.label_14 = QtWidgets.QLabel(self.Settings)
        self.label_14.setGeometry(QtCore.QRect(10, 480, 55, 31))
        self.label_14.setObjectName("label_14")
        self.pushButton_initialise_microscope = QtWidgets.QPushButton(self.Settings)
        self.pushButton_initialise_microscope.setGeometry(QtCore.QRect(190, 480, 141, 31))
        self.pushButton_initialise_microscope.setObjectName("pushButton_initialise_microscope")
        self.lineEdit_ip_address = QtWidgets.QLineEdit(self.Settings)
        self.lineEdit_ip_address.setGeometry(QtCore.QRect(70, 480, 111, 31))
        self.lineEdit_ip_address.setObjectName("lineEdit_ip_address")
        self.pushButton_move_stage = QtWidgets.QPushButton(self.Settings)
        self.pushButton_move_stage.setGeometry(QtCore.QRect(270, 330, 101, 21))
        self.pushButton_move_stage.setObjectName("pushButton_move_stage")
        self.label_50 = QtWidgets.QLabel(self.Settings)
        self.label_50.setGeometry(QtCore.QRect(370, 110, 31, 16))
        self.label_50.setObjectName("label_50")
        self.label_49 = QtWidgets.QLabel(self.Settings)
        self.label_49.setGeometry(QtCore.QRect(370, 140, 31, 16))
        self.label_49.setObjectName("label_49")
        self.label_9 = QtWidgets.QLabel(self.Settings)
        self.label_9.setGeometry(QtCore.QRect(370, 230, 31, 16))
        self.label_9.setObjectName("label_9")
        self.label_26 = QtWidgets.QLabel(self.Settings)
        self.label_26.setGeometry(QtCore.QRect(270, 200, 21, 16))
        self.label_26.setObjectName("label_26")
        self.doubleSpinBox_stage_z = QtWidgets.QDoubleSpinBox(self.Settings)
        self.doubleSpinBox_stage_z.setGeometry(QtCore.QRect(285, 168, 80, 22))
        self.doubleSpinBox_stage_z.setMinimum(-100000.0)
        self.doubleSpinBox_stage_z.setMaximum(100000.0)
        self.doubleSpinBox_stage_z.setObjectName("doubleSpinBox_stage_z")
        self.label_25 = QtWidgets.QLabel(self.Settings)
        self.label_25.setGeometry(QtCore.QRect(270, 170, 21, 16))
        self.label_25.setObjectName("label_25")
        self.label_27 = QtWidgets.QLabel(self.Settings)
        self.label_27.setGeometry(QtCore.QRect(270, 230, 21, 16))
        self.label_27.setObjectName("label_27")
        self.doubleSpinBox_stage_y = QtWidgets.QDoubleSpinBox(self.Settings)
        self.doubleSpinBox_stage_y.setGeometry(QtCore.QRect(285, 138, 80, 22))
        self.doubleSpinBox_stage_y.setMinimum(-100000.0)
        self.doubleSpinBox_stage_y.setMaximum(100000.0)
        self.doubleSpinBox_stage_y.setProperty("value", 0.0)
        self.doubleSpinBox_stage_y.setObjectName("doubleSpinBox_stage_y")
        self.label_35 = QtWidgets.QLabel(self.Settings)
        self.label_35.setGeometry(QtCore.QRect(370, 200, 31, 16))
        self.label_35.setObjectName("label_35")
        self.doubleSpinBox_stage_x = QtWidgets.QDoubleSpinBox(self.Settings)
        self.doubleSpinBox_stage_x.setGeometry(QtCore.QRect(285, 110, 80, 22))
        self.doubleSpinBox_stage_x.setMinimum(-100000.0)
        self.doubleSpinBox_stage_x.setMaximum(100000.0)
        self.doubleSpinBox_stage_x.setObjectName("doubleSpinBox_stage_x")
        self.checkBox_compucentric = QtWidgets.QCheckBox(self.Settings)
        self.checkBox_compucentric.setGeometry(QtCore.QRect(270, 310, 111, 20))
        self.checkBox_compucentric.setChecked(True)
        self.checkBox_compucentric.setObjectName("checkBox_compucentric")
        self.doubleSpinBox_stage_t = QtWidgets.QDoubleSpinBox(self.Settings)
        self.doubleSpinBox_stage_t.setGeometry(QtCore.QRect(285, 228, 80, 22))
        self.doubleSpinBox_stage_t.setMinimum(-100000.0)
        self.doubleSpinBox_stage_t.setMaximum(360.0)
        self.doubleSpinBox_stage_t.setObjectName("doubleSpinBox_stage_t")
        self.pushButton_update_stage_position = QtWidgets.QPushButton(self.Settings)
        self.pushButton_update_stage_position.setGeometry(QtCore.QRect(270, 260, 101, 31))
        self.pushButton_update_stage_position.setObjectName("pushButton_update_stage_position")
        self.label_36 = QtWidgets.QLabel(self.Settings)
        self.label_36.setGeometry(QtCore.QRect(370, 170, 31, 16))
        self.label_36.setObjectName("label_36")
        self.label_24 = QtWidgets.QLabel(self.Settings)
        self.label_24.setGeometry(QtCore.QRect(270, 140, 21, 16))
        self.label_24.setObjectName("label_24")
        self.comboBox_move_type = QtWidgets.QComboBox(self.Settings)
        self.comboBox_move_type.setGeometry(QtCore.QRect(270, 80, 131, 22))
        self.comboBox_move_type.setObjectName("comboBox_move_type")
        self.comboBox_move_type.addItem("")
        self.comboBox_move_type.addItem("")
        self.comboBox_move_type.addItem("")
        self.doubleSpinBox_stage_r = QtWidgets.QDoubleSpinBox(self.Settings)
        self.doubleSpinBox_stage_r.setGeometry(QtCore.QRect(285, 198, 80, 22))
        self.doubleSpinBox_stage_r.setMinimum(-100000.0)
        self.doubleSpinBox_stage_r.setMaximum(100000.0)
        self.doubleSpinBox_stage_r.setObjectName("doubleSpinBox_stage_r")
        self.label_23 = QtWidgets.QLabel(self.Settings)
        self.label_23.setGeometry(QtCore.QRect(270, 112, 21, 16))
        self.label_23.setObjectName("label_23")
        self.tabWidget.addTab(self.Settings, "")
        self.horizontalLayout.addWidget(self.frame_1)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_counter = QtWidgets.QLabel(self.frame)
        self.label_counter.setGeometry(QtCore.QRect(720, 595, 81, 31))
        self.label_counter.setText("")
        self.label_counter.setObjectName("label_counter")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.frame)
        self.tabWidget_2.setGeometry(QtCore.QRect(0, 0, 821, 721))
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.Electron = QtWidgets.QWidget()
        self.Electron.setObjectName("Electron")
        self.pushButton_save_file = QtWidgets.QPushButton(self.Electron)
        self.pushButton_save_file.setGeometry(QtCore.QRect(700, 660, 93, 25))
        self.pushButton_save_file.setObjectName("pushButton_save_file")
        self.pushButton_restore = QtWidgets.QPushButton(self.Electron)
        self.pushButton_restore.setGeometry(QtCore.QRect(680, 555, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_restore.setFont(font)
        self.pushButton_restore.setObjectName("pushButton_restore")
        self.label_67 = QtWidgets.QLabel(self.Electron)
        self.label_67.setGeometry(QtCore.QRect(190, 650, 31, 16))
        self.label_67.setObjectName("label_67")
        self.label_31 = QtWidgets.QLabel(self.Electron)
        self.label_31.setGeometry(QtCore.QRect(25, 650, 71, 16))
        self.label_31.setObjectName("label_31")
        self.pushButton_apply_clahe = QtWidgets.QPushButton(self.Electron)
        self.pushButton_apply_clahe.setGeometry(QtCore.QRect(570, 555, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_apply_clahe.setFont(font)
        self.pushButton_apply_clahe.setObjectName("pushButton_apply_clahe")
        self.label_11 = QtWidgets.QLabel(self.Electron)
        self.label_11.setGeometry(QtCore.QRect(410, 540, 55, 16))
        self.label_11.setObjectName("label_11")
        self.doubleSpinBox_pixel_size = QtWidgets.QDoubleSpinBox(self.Electron)
        self.doubleSpinBox_pixel_size.setGeometry(QtCore.QRect(85, 648, 101, 22))
        self.doubleSpinBox_pixel_size.setMinimum(0.0)
        self.doubleSpinBox_pixel_size.setMaximum(1000000000.0)
        self.doubleSpinBox_pixel_size.setObjectName("doubleSpinBox_pixel_size")
        self.spinBox_tile_grid_size = QtWidgets.QSpinBox(self.Electron)
        self.spinBox_tile_grid_size.setGeometry(QtCore.QRect(490, 562, 71, 21))
        self.spinBox_tile_grid_size.setMinimum(1)
        self.spinBox_tile_grid_size.setMaximum(9999)
        self.spinBox_tile_grid_size.setProperty("value", 16)
        self.spinBox_tile_grid_size.setObjectName("spinBox_tile_grid_size")
        self.label_7 = QtWidgets.QLabel(self.Electron)
        self.label_7.setGeometry(QtCore.QRect(480, 540, 71, 16))
        self.label_7.setObjectName("label_7")
        self.label_image_frame1 = QtWidgets.QLabel(self.Electron)
        self.label_image_frame1.setGeometry(QtCore.QRect(10, 10, 768, 512))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_image_frame1.sizePolicy().hasHeightForWidth())
        self.label_image_frame1.setSizePolicy(sizePolicy)
        self.label_image_frame1.setMinimumSize(QtCore.QSize(256, 256))
        self.label_image_frame1.setFrameShape(QtWidgets.QFrame.Box)
        self.label_image_frame1.setText("")
        self.label_image_frame1.setObjectName("label_image_frame1")
        self.pushButton_open_file = QtWidgets.QPushButton(self.Electron)
        self.pushButton_open_file.setGeometry(QtCore.QRect(700, 630, 93, 25))
        self.pushButton_open_file.setObjectName("pushButton_open_file")
        self.spinBox_clip_limit = QtWidgets.QSpinBox(self.Electron)
        self.spinBox_clip_limit.setGeometry(QtCore.QRect(410, 562, 71, 21))
        self.spinBox_clip_limit.setMinimum(1)
        self.spinBox_clip_limit.setMaximum(9999)
        self.spinBox_clip_limit.setProperty("value", 10)
        self.spinBox_clip_limit.setObjectName("spinBox_clip_limit")
        self.pushButton_acquire = QtWidgets.QPushButton(self.Electron)
        self.pushButton_acquire.setGeometry(QtCore.QRect(10, 530, 101, 81))
        self.pushButton_acquire.setObjectName("pushButton_acquire")
        self.pushButton_last_image = QtWidgets.QPushButton(self.Electron)
        self.pushButton_last_image.setGeometry(QtCore.QRect(120, 530, 101, 81))
        self.pushButton_last_image.setObjectName("pushButton_last_image")
        self.tabWidget_2.addTab(self.Electron, "")
        self.horizontalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1319, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_as = QtWidgets.QAction(MainWindow)
        self.actionSave_as.setObjectName("actionSave_as")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_as)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_10.setText(_translate("MainWindow", "messages"))
        self.label_3.setText(_translate("MainWindow", "Horizontal field width, µm"))
        self.label_2.setText(_translate("MainWindow", "dwell time, µs"))
        self.pushButton_select_directory.setText(_translate("MainWindow", "select directory"))
        self.comboBox_resolution.setItemText(0, _translate("MainWindow", "1536x1024"))
        self.comboBox_resolution.setItemText(1, _translate("MainWindow", "1024x884"))
        self.comboBox_resolution.setItemText(2, _translate("MainWindow", "2048x1768"))
        self.comboBox_resolution.setItemText(3, _translate("MainWindow", "3072x2048"))
        self.comboBox_resolution.setItemText(4, _translate("MainWindow", "4096x3536"))
        self.comboBox_resolution.setItemText(5, _translate("MainWindow", "512x442"))
        self.comboBox_resolution.setItemText(6, _translate("MainWindow", "6144x4096"))
        self.comboBox_resolution.setItemText(7, _translate("MainWindow", "768x512"))
        self.label_28.setText(_translate("MainWindow", "Resolution"))
        self.checkBox_autocontrast.setText(_translate("MainWindow", "autocontrast"))
        self.checkBox_drift_correction.setText(_translate("MainWindow", "drift correction"))
        self.comboBox_beam_type.setItemText(0, _translate("MainWindow", "Electron"))
        self.comboBox_beam_type.setItemText(1, _translate("MainWindow", "Ion"))
        self.label_4.setText(_translate("MainWindow", "Beam"))
        self.comboBox_quadrant.setItemText(0, _translate("MainWindow", "1"))
        self.comboBox_quadrant.setItemText(1, _translate("MainWindow", "2"))
        self.comboBox_quadrant.setItemText(2, _translate("MainWindow", "3"))
        self.comboBox_quadrant.setItemText(3, _translate("MainWindow", "4"))
        self.label_8.setText(_translate("MainWindow", "Quadrant"))
        self.label_5.setText(_translate("MainWindow", "horizontal field width , µm"))
        self.pushButton_abort_stack_collection.setText(_translate("MainWindow", "Abort"))
        self.pushButton_collect_stack.setText(_translate("MainWindow", "collect stack"))
        self.plainTextEdit_sample_name.setPlainText(_translate("MainWindow", "sample_name"))
        self.label_12.setText(_translate("MainWindow", "Frame integration"))
        self.label_13.setText(_translate("MainWindow", "magnification x"))
        self.label_hfw_01.setText(_translate("MainWindow", "1M"))
        self.label_hfw_02.setText(_translate("MainWindow", "800k"))
        self.label_hfw_03.setText(_translate("MainWindow", "500k"))
        self.label_hfw_04.setText(_translate("MainWindow", "250k"))
        self.label_hfw_05.setText(_translate("MainWindow", "100k"))
        self.label_hfw_06.setText(_translate("MainWindow", "50k"))
        self.label_hfw_07.setText(_translate("MainWindow", "20k"))
        self.label_hfw_08.setText(_translate("MainWindow", "10k"))
        self.label_hfw_09.setText(_translate("MainWindow", "5k"))
        self.label_hfw_10.setText(_translate("MainWindow", "2.5k"))
        self.label_hfw_11.setText(_translate("MainWindow", "1k"))
        self.label_hfw_12.setText(_translate("MainWindow", "500"))
        self.checkBox_q1.setText(_translate("MainWindow", "Q1"))
        self.checkBox_q2.setText(_translate("MainWindow", "Q2"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.SEM), _translate("MainWindow", "SEM"))
        self.label_16.setText(_translate("MainWindow", "Magnification"))
        self.label_17.setText(_translate("MainWindow", "High voltage V"))
        self.label_18.setText(_translate("MainWindow", "WD mm"))
        self.label_19.setText(_translate("MainWindow", "Brightness %"))
        self.label_20.setText(_translate("MainWindow", "Contrast %"))
        self.label_21.setText(_translate("MainWindow", "Beam current nA"))
        self.pushButton_update_SEM_state.setText(_translate("MainWindow", "Update SEM state"))
        self.label_32.setText(_translate("MainWindow", "Average"))
        self.label_29.setText(_translate("MainWindow", "Bit depth"))
        self.comboBox_bit_depth.setItemText(0, _translate("MainWindow", "8"))
        self.comboBox_bit_depth.setItemText(1, _translate("MainWindow", "16"))
        self.label_14.setText(_translate("MainWindow", "ip adress"))
        self.pushButton_initialise_microscope.setText(_translate("MainWindow", "Initialise microscope"))
        self.lineEdit_ip_address.setText(_translate("MainWindow", "192.168.0.1"))
        self.pushButton_move_stage.setText(_translate("MainWindow", "Move to position"))
        self.label_50.setText(_translate("MainWindow", "µm"))
        self.label_49.setText(_translate("MainWindow", "µm"))
        self.label_9.setText(_translate("MainWindow", "deg"))
        self.label_26.setText(_translate("MainWindow", "R"))
        self.label_25.setText(_translate("MainWindow", "Z"))
        self.label_27.setText(_translate("MainWindow", "T"))
        self.label_35.setText(_translate("MainWindow", "deg"))
        self.checkBox_compucentric.setText(_translate("MainWindow", "compucentric"))
        self.pushButton_update_stage_position.setText(_translate("MainWindow", "Get position"))
        self.label_36.setText(_translate("MainWindow", "µm"))
        self.label_24.setText(_translate("MainWindow", "Y"))
        self.comboBox_move_type.setItemText(0, _translate("MainWindow", "Relative"))
        self.comboBox_move_type.setItemText(1, _translate("MainWindow", "Absolute"))
        self.comboBox_move_type.setItemText(2, _translate("MainWindow", "Raw coordinates"))
        self.label_23.setText(_translate("MainWindow", "X"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Settings), _translate("MainWindow", "Settings"))
        self.pushButton_save_file.setText(_translate("MainWindow", "Save file"))
        self.pushButton_restore.setText(_translate("MainWindow", "restore"))
        self.label_67.setText(_translate("MainWindow", "nm"))
        self.label_31.setText(_translate("MainWindow", "pixel size"))
        self.pushButton_apply_clahe.setText(_translate("MainWindow", "Apply CLAHE"))
        self.label_11.setText(_translate("MainWindow", "clip limit"))
        self.label_7.setText(_translate("MainWindow", "tile grid size"))
        self.pushButton_open_file.setText(_translate("MainWindow", "Open file"))
        self.pushButton_acquire.setText(_translate("MainWindow", "Acquire"))
        self.pushButton_last_image.setText(_translate("MainWindow", "Last image"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.Electron), _translate("MainWindow", "SEM"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave_as.setText(_translate("MainWindow", "Save as"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))

